### ISSUE TITLE
Integration in git-Skripte

### ISSUE THREAD

**Issue by kronn** [severinraez/muschelskripte#1]
Werter Herr @severinraez

Nach allfälliger Durchsicht der hier feilgebotenen Muschelskripte ist mir ein miniskules Manko aufgefallen. Das Skript mit dem Namen `git_overview` kann in der dargeboteten Benennung nur als solches, `git_overview` aufgerufen und ausgeführt werden. Dies mag für manche ausreichend sein, ich jedoch, prangere dies an.  Zur besseren Integration in die Erwartungs- und Erfahrungswelt eines git-Benutzers empfehle ich, den Namen zu `git-overview` zu benennen. Dies führt dazu, dass - sofern sich das Skipt im Pfad befindet - das es auch als `git overview` verfügbar ist. Ferner kann es per Tabulator - oder den lokal eingestellten Vervollständigsauslöser - auch vervollständigt werden, sollte man es nur teilweise, aber eindeutig eingegeben haben.

In der Hoffnung, dass Sie diesen eklatanten Mangel demallernächst beheben, verbleibe ich

Hochachtungsvoll
@kronn

**Comment by severinraez** [comment]
Lieber Herr @kronn 

Jesses! Sie liegen völlig im Recht. Ich habe diese Probleminstanz mit einem entsprechenden Etikett versehen. Darüber hinausgehende Massnahmen erlaube ich mir aber bis zu den nächsten Anpassungen an meinem Arbeitsfluss im Allgemeinen un der Funktionalität dieses Skripts im Speziellen zu verschieben - und sei es nur, um der GitHub-Bürokratie frönen zu können.

Mit tiefster Verneigung
@severinraez
